name: Build iOS IPA

on:
  push:
    branches:
      - main   # Change if your branch name is not "main"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'   # Set your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build unsigned IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
